"""Initial migration

Revision ID: 4f39976bea79
Revises: 86db401b1ec1
Create Date: 2026-02-23 21:33:24.388934

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f39976bea79'
down_revision = '86db401b1ec1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('sleep_hours',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('caffeine_per_day',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('daily_screen_time',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('stress_level',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('physical_activity',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('physical_activity',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('stress_level',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('daily_screen_time',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('caffeine_per_day',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('sleep_hours',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
